import { describe, it, expect } from 'vitest';
import {
  parseVideo,
  parseArtTrackDescription,
  cleanTitle,
  extractMovie,
  topicChannelArtist,
  SOURCE,
} from './ytTrackParse.js';
import {
  matchVideo,
  scoreCandidate,
  fingerprint,
  fingerprintKeys,
  TIER,
} from './ytMatch.js';

// A JioSaavn candidate in `mapSong` shape (catalog.js:82). `artist` is ONE
// string but often a comma-joined list, and `language` is passed through raw —
// both are why the scorer tokenises and lowercases rather than comparing whole
// strings.
const song = o => ({
  id: 'x',
  title: '',
  artist: '',
  album: null,
  language: null,
  durationSec: null,
  ...o,
});

const ART_DESC = `Provided to YouTube by Universal Music Group

Kesariya (From "Brahmastra") · Pritam · Arijit Singh · Amitabh Bhattacharya

Brahmastra

℗ 2022 Sony Music Entertainment India Pvt. Ltd.

Released on: 2022-07-17

Auto-generated by YouTube.`;

describe('tier 1 — Art Track descriptions', () => {
  it('reads track, artists, album and year from the credit block', () => {
    const r = parseArtTrackDescription(ART_DESC);
    expect(r.title).toBe('Kesariya');
    expect(r.artists).toEqual(['Pritam', 'Arijit Singh', 'Amitabh Bhattacharya']);
    expect(r.album).toBe('Brahmastra');
    expect(r.year).toBe(2022);
  });

  it('returns null when the block is absent, so tier 2 can take over', () => {
    expect(parseArtTrackDescription('just a normal description')).toBeNull();
  });

  it('marks the source so duration can be trusted differently', () => {
    const p = parseVideo({
      title: 'anything',
      channelTitle: 'Pritam - Topic',
      description: ART_DESC,
    });
    expect(p.source).toBe(SOURCE.ART_TRACK);
    expect(p.title).toBe('Kesariya');
  });

  it('reads a Topic channel as a high-confidence artist', () => {
    expect(topicChannelArtist('Arijit Singh - Topic')).toBe('Arijit Singh');
    expect(topicChannelArtist('T-Series')).toBeNull();
  });
});

describe('tier 2 — ugly real-world titles', () => {
  it.each([
    ['Kesariya (Official Video) | Brahmastra | Ranbir Kapoor', 'Kesariya'],
    ['Naatu Naatu (Full Video Song) [4K]', 'Naatu Naatu'],
    ['Tum Hi Ho - Aashiqui 2 (Lyrical) HD', 'Tum Hi Ho - Aashiqui 2'],
    ['Shape of You (Official Music Video)', 'Shape of You'],
    ['Blinding Lights [Lyrics] 🔥🔥', 'Blinding Lights'],
    ['Believer - Imagine Dragons (Audio)', 'Believer - Imagine Dragons'],
    // Regression: the bare feat-strip used to leave an orphan "(" here,
    // producing "Perfect (". Bracketed credits must be removed whole.
    ['Perfect (feat. Beyoncé) (Official Audio)', 'Perfect'],

    // The four below are VERBATIM titles from live RD mix responses captured
    // 2026-08-14. Two of them were parsed wrongly before those responses
    // existed, which is the argument for testing against real data rather than
    // titles I invented.
    //
    // Amateur reupload separating credits with RUNS OF SPACES where a label
    // would use pipes. Previously the entire credit list became the title.
    [
      'Munjane Manjalli   Audio Song   Just Maath Maathali   Kiccha Sudeep   Ramya   Raghu Dixit',
      'Munjane Manjalli',
    ],
    // "Full Video Song" was eaten by the shorter "full video" pattern, leaving
    // a stranded "Song": "Gira Gira Song".
    [
      'Gira Gira Full Video Song | Dear Comrade Tamil | Vijay Deverakonda | Rashmika | Bharat Kamma',
      'Gira Gira',
    ],
    [
      'Nee Amrithadhare Lyrical | Harish | Supriya Acharya | Dhyan | Ramya | Manomurthy | Amrithadhare',
      'Nee Amrithadhare',
    ],
    [
      'Oo Saathiya Lyrical | Love Reddy | Anjan Ramachendra, Shravani | Smaran Reddy | Prince Henry',
      'Oo Saathiya',
    ],
  ])('cleans %s', (raw, want) => {
    expect(cleanTitle(raw)).toBe(want);
  });

  it('splits Artist - Title on the first hyphen', () => {
    const p = parseVideo({
      title: 'Imagine Dragons - Believer',
      channelTitle: 'ImagineDragonsVEVO',
    });
    expect(p.artists).toEqual(['Imagine Dragons']);
    expect(p.title).toBe('Believer');
  });
});

describe('(From "Movie") is a signal on both sides, not noise', () => {
  it('extracts with straight quotes', () => {
    const r = extractMovie('Kesariya (From "Brahmastra")');
    expect(r.movie).toBe('Brahmastra');
    expect(r.rest).toBe('Kesariya');
  });

  it('extracts with curly quotes — the provider uses both', () => {
    expect(extractMovie('Kesariya (From “Brahmastra”)').movie).toBe('Brahmastra');
  });
});

describe('scoring', () => {
  const kesariya = parseVideo({
    title: 'x',
    channelTitle: 'Pritam - Topic',
    description: ART_DESC,
    durationSec: 268,
  });

  it('auto-accepts an exact Art Track match', () => {
    const r = matchVideo(kesariya, [
      song({
        id: 'a',
        title: 'Kesariya (From "Brahmastra")',
        artist: 'Pritam, Arijit Singh',
        album: 'Brahmastra',
        language: 'hindi',
        durationSec: 268,
      }),
    ]);
    expect(r.tier).toBe(TIER.AUTO);
  });

  // The single most likely wrong auto-accept in this catalog: a lofi remix
  // agrees on title, artist, language AND duration. A subtractive penalty still
  // lets it clear 0.85 — only a hard cap makes it impossible.
  it('never auto-accepts a lofi remix against the original', () => {
    const lofi = parseVideo({
      title: 'Kesariya Lofi Remix',
      channelTitle: 'Chill Beats',
      durationSec: 268,
    });
    const r = matchVideo(lofi, [
      song({
        title: 'Kesariya (From "Brahmastra")',
        artist: 'Pritam, Arijit Singh',
        language: 'hindi',
        durationSec: 268,
      }),
    ]);
    expect(r.tier).not.toBe(TIER.AUTO);
    expect(r.best.caps).toContain('version');
    expect(r.best.score).toBeLessThanOrEqual(0.55);
  });

  it('never auto-accepts on title alone with no artist agreement', () => {
    const p = parseVideo({
      title: 'Kesariya',
      channelTitle: 'Random Uploads',
      durationSec: 268,
    });
    const r = matchVideo(p, [
      song({ title: 'Kesariya', artist: 'Some Other Singer', durationSec: 268 }),
    ]);
    expect(r.tier).not.toBe(TIER.AUTO);
  });

  it('caps a cross-language duplicate below auto', () => {
    const r = matchVideo({ ...kesariya, language: 'hindi' }, [
      song({
        title: 'Kesariya',
        artist: 'Pritam, Arijit Singh',
        language: 'telugu',
        durationSec: 268,
      }),
    ]);
    expect(r.best.caps).toContain('language');
    expect(r.tier).not.toBe(TIER.AUTO);
  });

  it('tolerates a music video running long, but not an Art Track', () => {
    const mv = parseVideo({
      title: 'Naatu Naatu - RRR',
      channelTitle: 'T-Series',
      durationSec: 343, // +75s of intro and credits
    });
    const cand = song({
      title: 'Naatu Naatu',
      artist: 'Rahul Sipligunj',
      durationSec: 268,
    });
    const asVideo = scoreCandidate(mv, cand);
    const asArtTrack = scoreCandidate({ ...mv, source: SOURCE.ART_TRACK }, cand);
    expect(asVideo.breakdown.duration).toBeGreaterThan(
      asArtTrack.breakdown.duration,
    );
  });

  it('treats 40s off as fatal for an Art Track', () => {
    const s = scoreCandidate(
      kesariya,
      song({ title: 'Kesariya', artist: 'Pritam', durationSec: 228 }),
    );
    expect(s.breakdown.duration).toBe(0);
  });

  it('matches a comma-joined candidate artist', () => {
    const s = scoreCandidate(
      kesariya,
      song({
        title: 'Kesariya',
        artist: 'Pritam, Arijit Singh, Amitabh Bhattacharya',
        durationSec: 268,
      }),
    );
    expect(s.breakdown.artist).toBeGreaterThan(0);
  });

  it('returns unmatched when nothing is close', () => {
    const r = matchVideo(kesariya, [
      song({ title: 'Totally Different Song', artist: 'Nobody', durationSec: 100 }),
    ]);
    expect(r.tier).toBe(TIER.UNMATCHED);
  });

  it('offers at most three candidates for review', () => {
    const many = Array.from({ length: 8 }, (_, i) =>
      song({ id: `c${i}`, title: 'Kesariya', artist: 'Pritam', durationSec: 268 }),
    );
    expect(matchVideo(kesariya, many).candidates).toHaveLength(3);
  });
});

describe('fingerprint cache key', () => {
  const kesariya = parseVideo({
    title: 'x',
    channelTitle: 'Pritam - Topic',
    description: ART_DESC,
    durationSec: 268,
  });

  // Two encodes of one song can straddle a bucket boundary (268s → 54,
  // 266s → 53). Widening the bucket only moves the boundary, so the LOOKUP
  // checks neighbours. A miss here costs one extra search, never a bad match.
  it('collapses two uploads of one song via neighbour keys', () => {
    const vevo = {
      source: SOURCE.MUSIC_VIDEO,
      title: 'Kesariya',
      artists: ['Pritam'],
      durationSec: 266,
      versions: [],
    };
    expect(fingerprintKeys(kesariya)).toContain(fingerprint(vevo));
  });

  it('separates different songs', () => {
    const other = {
      source: SOURCE.UNKNOWN,
      title: 'Naatu Naatu',
      artists: ['Pritam'],
      durationSec: 268,
      versions: [],
    };
    expect(fingerprint(kesariya)).not.toBe(fingerprint(other));
  });
});
