import { describe, it, expect } from 'vitest';
import {
  parseVideo,
  parseVideoVariants,
  isGenericTitle,
  stripTrailingDecoration,
  parseArtTrackDescription,
  cleanTitle,
  extractMovie,
  movieFromPipeSegments,
  topicChannelArtist,
  SOURCE,
} from './ytTrackParse.js';
import {
  matchVideo,
  scoreCandidate,
  titleSimilarity,
  tokensAlike,
  artistOverlap,
  fingerprint,
  fingerprintKeys,
  TIER,
} from './ytMatch.js';

// A JioSaavn candidate in `mapSong` shape (catalog.js:82). `artist` is ONE
// string but often a comma-joined list, and `language` is passed through raw —
// both are why the scorer tokenises and lowercases rather than comparing whole
// strings.
const song = o => ({
  id: 'x',
  title: '',
  artist: '',
  album: null,
  language: null,
  durationSec: null,
  ...o,
});

const ART_DESC = `Provided to YouTube by Universal Music Group

Kesariya (From "Brahmastra") · Pritam · Arijit Singh · Amitabh Bhattacharya

Brahmastra

℗ 2022 Sony Music Entertainment India Pvt. Ltd.

Released on: 2022-07-17

Auto-generated by YouTube.`;

describe('tier 1 — Art Track descriptions', () => {
  it('reads track, artists, album and year from the credit block', () => {
    const r = parseArtTrackDescription(ART_DESC);
    expect(r.title).toBe('Kesariya');
    expect(r.artists).toEqual(['Pritam', 'Arijit Singh', 'Amitabh Bhattacharya']);
    expect(r.album).toBe('Brahmastra');
    expect(r.year).toBe(2022);
  });

  it('returns null when the block is absent, so tier 2 can take over', () => {
    expect(parseArtTrackDescription('just a normal description')).toBeNull();
  });

  it('marks the source so duration can be trusted differently', () => {
    const p = parseVideo({
      title: 'anything',
      channelTitle: 'Pritam - Topic',
      description: ART_DESC,
    });
    expect(p.source).toBe(SOURCE.ART_TRACK);
    expect(p.title).toBe('Kesariya');
  });

  it('reads a Topic channel as a high-confidence artist', () => {
    expect(topicChannelArtist('Arijit Singh - Topic')).toBe('Arijit Singh');
    expect(topicChannelArtist('T-Series')).toBeNull();
  });
});

describe('tier 2 — ugly real-world titles', () => {
  it.each([
    ['Kesariya (Official Video) | Brahmastra | Ranbir Kapoor', 'Kesariya'],
    ['Naatu Naatu (Full Video Song) [4K]', 'Naatu Naatu'],
    ['Tum Hi Ho - Aashiqui 2 (Lyrical) HD', 'Tum Hi Ho - Aashiqui 2'],
    ['Shape of You (Official Music Video)', 'Shape of You'],
    ['Blinding Lights [Lyrics] 🔥🔥', 'Blinding Lights'],
    ['Believer - Imagine Dragons (Audio)', 'Believer - Imagine Dragons'],
    // Regression: the bare feat-strip used to leave an orphan "(" here,
    // producing "Perfect (". Bracketed credits must be removed whole.
    ['Perfect (feat. Beyoncé) (Official Audio)', 'Perfect'],

    // The four below are VERBATIM titles from live RD mix responses captured
    // 2026-08-14. Two of them were parsed wrongly before those responses
    // existed, which is the argument for testing against real data rather than
    // titles I invented.
    //
    // Amateur reupload separating credits with RUNS OF SPACES where a label
    // would use pipes. Previously the entire credit list became the title.
    [
      'Munjane Manjalli   Audio Song   Just Maath Maathali   Kiccha Sudeep   Ramya   Raghu Dixit',
      'Munjane Manjalli',
    ],
    // "Full Video Song" was eaten by the shorter "full video" pattern, leaving
    // a stranded "Song": "Gira Gira Song".
    [
      'Gira Gira Full Video Song | Dear Comrade Tamil | Vijay Deverakonda | Rashmika | Bharat Kamma',
      'Gira Gira',
    ],
    [
      'Nee Amrithadhare Lyrical | Harish | Supriya Acharya | Dhyan | Ramya | Manomurthy | Amrithadhare',
      'Nee Amrithadhare',
    ],
    [
      'Oo Saathiya Lyrical | Love Reddy | Anjan Ramachendra, Shravani | Smaran Reddy | Prince Henry',
      'Oo Saathiya',
    ],
  ])('cleans %s', (raw, want) => {
    expect(cleanTitle(raw)).toBe(want);
  });

  it('splits Artist - Title on the first hyphen', () => {
    const p = parseVideo({
      title: 'Imagine Dragons - Believer',
      channelTitle: 'ImagineDragonsVEVO',
    });
    expect(p.artists).toEqual(['Imagine Dragons']);
    expect(p.title).toBe('Believer');
  });
});

describe('(From "Movie") is a signal on both sides, not noise', () => {
  it('extracts with straight quotes', () => {
    const r = extractMovie('Kesariya (From "Brahmastra")');
    expect(r.movie).toBe('Brahmastra');
    expect(r.rest).toBe('Kesariya');
  });

  it('extracts with curly quotes — the provider uses both', () => {
    expect(extractMovie('Kesariya (From “Brahmastra”)').movie).toBe('Brahmastra');
  });
});

describe('scoring', () => {
  const kesariya = parseVideo({
    title: 'x',
    channelTitle: 'Pritam - Topic',
    description: ART_DESC,
    durationSec: 268,
  });

  it('auto-accepts an exact Art Track match', () => {
    const r = matchVideo(kesariya, [
      song({
        id: 'a',
        title: 'Kesariya (From "Brahmastra")',
        artist: 'Pritam, Arijit Singh',
        album: 'Brahmastra',
        language: 'hindi',
        durationSec: 268,
      }),
    ]);
    expect(r.tier).toBe(TIER.AUTO);
  });

  // The single most likely wrong auto-accept in this catalog: a lofi remix
  // agrees on title, artist, language AND duration. A subtractive penalty still
  // lets it clear 0.85 — only a hard cap makes it impossible.
  it('never auto-accepts a lofi remix against the original', () => {
    const lofi = parseVideo({
      title: 'Kesariya Lofi Remix',
      channelTitle: 'Chill Beats',
      durationSec: 268,
    });
    const r = matchVideo(lofi, [
      song({
        title: 'Kesariya (From "Brahmastra")',
        artist: 'Pritam, Arijit Singh',
        language: 'hindi',
        durationSec: 268,
      }),
    ]);
    expect(r.tier).not.toBe(TIER.AUTO);
    expect(r.best.caps).toContain('version');
    expect(r.best.score).toBeLessThanOrEqual(0.55);
  });

  // MEASURED on a real 50-track mix: 45 titles yield NO artist, and those were
  // overwhelmingly correct matches stuck at 0.611 in review. So "no artist"
  // cannot block auto-accept. What must block it is AMBIGUITY — two candidates
  // we cannot separate without an artist.
  it('auto-accepts an artist-less match when it is unambiguous and duration is exact', () => {
    const p = parseVideo({
      title: 'Gudugudiya Sedi Nodo',
      channelTitle: 'Raghu Dixit Music',
      durationSec: 268,
    });
    const r = matchVideo(p, [
      song({ title: 'Gudugudiya Sedi Nodo', artist: 'Raghu Dixit', durationSec: 268 }),
    ]);
    expect(r.best.breakdown.artist).toBeNull(); // unknown, not disagreeing
    expect(r.tier).toBe(TIER.AUTO);
  });

  // The ambiguity guard was TRIED AND REMOVED — see the note in matchVideo.
  // Three measured runs, two patches: it blocked correct matches every time and
  // never prevented a wrong one, ending with a perfect 1.000 sent to review.
  //
  // This test now pins the DECISION that replaced it: when metadata genuinely
  // cannot separate two candidates, take the catalog's own ranking rather than
  // refusing to choose. searchSongs returns them ranked and the first is the
  // canonical entry far more often than not.
  it('resolves a genuine tie by catalog order instead of refusing', () => {
    // Two masters 12s apart: outside any meaningful same-recording window, both
    // inside the music-video duration tolerance, so they score IDENTICALLY.
    const p = parseVideo({ title: 'Uyire', channelTitle: 'Label', durationSec: 240 });
    const r = matchVideo(p, [
      song({ id: 'first', title: 'Uyire', artist: 'Singer One', durationSec: 240 }),
      song({ id: 'second', title: 'Uyire', artist: 'Singer Two', durationSec: 252 }),
    ]);
    expect(r.candidates[0].score).toBe(r.candidates[1].score); // genuinely tied
    expect(r.tier).toBe(TIER.AUTO);
    expect(r.best.candidate.id).toBe('first'); // catalog order wins
  });

  // The protections that DID earn their place stay, and this is the line
  // between them: a tie is chosen, a contradiction is not.
  it('still refuses when the evidence actively disagrees', () => {
    const p = parseVideo({ title: 'Uyire', channelTitle: 'Label', durationSec: 240 });
    const r = matchVideo(p, [
      // Right title, but 4 minutes adrift — that is a different recording.
      song({ id: 'a', title: 'Uyire', artist: 'Someone', durationSec: 480 }),
    ]);
    expect(r.tier).not.toBe(TIER.AUTO);
  });

  it('treats the same recording under two credits as one candidate', () => {
    const p = parseVideo({ title: 'Naan Pizhai', channelTitle: 'Label', durationSec: 240 });
    const r = matchVideo(p, [
      song({ id: 'composer', title: 'Naan Pizhai', artist: 'Anirudh Ravichander', durationSec: 240 }),
      song({ id: 'singer', title: 'Naan Pizhai', artist: 'Sid Sriram', durationSec: 240 }),
    ]);
    expect(r.tier).toBe(TIER.AUTO);
  });

  it('still blocks a match whose artist is known and DISAGREES', () => {
    const p = parseVideo({ title: 'Imagine Dragons - Believer', channelTitle: 'x', durationSec: 204 });
    const r = matchVideo(p, [
      song({ title: 'Believer', artist: 'Completely Different Person', durationSec: 204 }),
    ]);
    expect(r.best.breakdown.artist).toBe(0); // known, disagreeing
    expect(r.tier).not.toBe(TIER.AUTO);
  });

  it('caps a cross-language duplicate below auto', () => {
    const r = matchVideo({ ...kesariya, language: 'hindi' }, [
      song({
        title: 'Kesariya',
        artist: 'Pritam, Arijit Singh',
        language: 'telugu',
        durationSec: 268,
      }),
    ]);
    expect(r.best.caps).toContain('language');
    expect(r.tier).not.toBe(TIER.AUTO);
  });

  it('tolerates a music video running long, but not an Art Track', () => {
    const mv = parseVideo({
      title: 'Naatu Naatu - RRR',
      channelTitle: 'T-Series',
      durationSec: 343, // +75s of intro and credits
    });
    const cand = song({
      title: 'Naatu Naatu',
      artist: 'Rahul Sipligunj',
      durationSec: 268,
    });
    const asVideo = scoreCandidate(mv, cand);
    const asArtTrack = scoreCandidate({ ...mv, source: SOURCE.ART_TRACK }, cand);
    expect(asVideo.breakdown.duration).toBeGreaterThan(
      asArtTrack.breakdown.duration,
    );
  });

  it('treats 40s off as fatal for an Art Track', () => {
    const s = scoreCandidate(
      kesariya,
      song({ title: 'Kesariya', artist: 'Pritam', durationSec: 228 }),
    );
    expect(s.breakdown.duration).toBe(0);
  });

  it('matches a comma-joined candidate artist', () => {
    const s = scoreCandidate(
      kesariya,
      song({
        title: 'Kesariya',
        artist: 'Pritam, Arijit Singh, Amitabh Bhattacharya',
        durationSec: 268,
      }),
    );
    expect(s.breakdown.artist).toBeGreaterThan(0);
  });

  it('returns unmatched when nothing is close', () => {
    const r = matchVideo(kesariya, [
      song({ title: 'Totally Different Song', artist: 'Nobody', durationSec: 100 }),
    ]);
    expect(r.tier).toBe(TIER.UNMATCHED);
  });

  it('offers at most three candidates for review', () => {
    const many = Array.from({ length: 8 }, (_, i) =>
      song({ id: `c${i}`, title: 'Kesariya', artist: 'Pritam', durationSec: 268 }),
    );
    expect(matchVideo(kesariya, many).candidates).toHaveLength(3);
  });
});

describe('fingerprint cache key', () => {
  const kesariya = parseVideo({
    title: 'x',
    channelTitle: 'Pritam - Topic',
    description: ART_DESC,
    durationSec: 268,
  });

  // Two encodes of one song can straddle a bucket boundary (268s → 54,
  // 266s → 53). Widening the bucket only moves the boundary, so the LOOKUP
  // checks neighbours. A miss here costs one extra search, never a bad match.
  it('collapses two uploads of one song via neighbour keys', () => {
    const vevo = {
      source: SOURCE.MUSIC_VIDEO,
      title: 'Kesariya',
      artists: ['Pritam'],
      durationSec: 266,
      versions: [],
    };
    expect(fingerprintKeys(kesariya)).toContain(fingerprint(vevo));
  });

  it('separates different songs', () => {
    const other = {
      source: SOURCE.UNKNOWN,
      title: 'Naatu Naatu',
      artists: ['Pritam'],
      durationSec: 268,
      versions: [],
    };
    expect(fingerprint(kesariya)).not.toBe(fingerprint(other));
  });
});

// All four titles below are VERBATIM from the first real dry run, where they
// produced wrong or unusable parses.
describe('ambiguous "A - B", measured both ways', () => {
  it.each([
    ['Title Track', true],
    ['Title Track Video', true],
    ['Official', true],
    ['Theme', true],
    ['Gudugudiya Sedi Nodo', false],
    ['Tulasi', false],
  ])('isGenericTitle(%s) === %s', (t, want) => {
    expect(isGenericTitle(t)).toBe(want);
  });

  // Indian norm: song first. Guessing the Western order made the catalog search
  // look for an artist name and find nothing.
  it('offers both readings of "Tulasi - Sumedh K"', () => {
    const v = parseVideoVariants({ title: 'Tulasi - Sumedh K', channelTitle: 'x' });
    expect(v).toHaveLength(2);
    expect(v.map(p => p.title)).toEqual(expect.arrayContaining(['Tulasi', 'Sumedh K']));
  });

  // A generic head is not ambiguous, it is wrong — so the swap must LEAD.
  it('leads with the swap when the head is generic', () => {
    const v = parseVideoVariants({ title: 'Title Track - Mugulu Nage', channelTitle: 'x' });
    expect(v[0].title).toBe('Mugulu Nage');
  });

  it('does not guess at all for an Art Track — credits are structured', () => {
    const v = parseVideoVariants({
      title: 'whatever', channelTitle: 'Pritam - Topic', description: ART_DESC,
    });
    expect(v).toHaveLength(1);
  });

  it('picks the reading the CATALOG supports, not the one we guessed', () => {
    const variants = parseVideoVariants({ title: 'Tulasi - Sumedh K', channelTitle: 'x', durationSec: 200 });
    const r = matchVideo(variants, [
      song({ id: 'right', title: 'Tulasi', artist: 'Sumedh K', durationSec: 200 }),
    ]);
    expect(r.best.candidate.id).toBe('right');
    expect(r.best.parsed.title).toBe('Tulasi');
  });

  it('never offers the same song twice in the top three', () => {
    const variants = parseVideoVariants({ title: 'Tulasi - Sumedh K', channelTitle: 'x', durationSec: 200 });
    const r = matchVideo(variants, [
      song({ id: 'a', title: 'Tulasi', artist: 'Sumedh K', durationSec: 200 }),
      song({ id: 'b', title: 'Tulasi', artist: 'Someone Else', durationSec: 200 }),
    ]);
    const ids = r.candidates.map(c => c.candidate.id);
    expect(new Set(ids).size).toBe(ids.length);
  });
});

// Every case below is verbatim from the second real dry run (20% auto), where
// each was a CORRECT match blocked by a different defect.
describe('defects found by the second measured run', () => {
  it('does not let a duplicate listing count as a rival candidate', () => {
    // Six rows scored 0.917 with exact duration and went to review because
    // JioSaavn returned the same recording twice and the runner-up tied.
    const p = parseVideo({ title: 'Urugi Urugi', channelTitle: 'Label', durationSec: 240 });
    const r = matchVideo(p, [
      song({ id: 'a', title: 'Urugi Urugi', artist: 'Vignesh Ramakrishna', durationSec: 240 }),
      song({ id: 'b', title: 'Urugi Urugi', artist: 'Vignesh Ramakrishna', album: 'Other', durationSec: 240 }),
    ]);
    expect(r.tier).toBe(TIER.AUTO);
  });

  it('treats a film name parsed as an artist as unknown, not as disagreement', () => {
    // "Anbil Avan - Vinnaithaandi Varuvaayaa": the tail is the MOVIE. Scoring
    // it 0 against the real singer blocked a perfect title + duration match.
    //
    // Note this goes through parseVideoVariants + matchVideo, the real path.
    // The PRIMARY reading takes the film as the title; it is the swapped
    // reading that needs the demotion, and only matchVideo sees both.
    const variants = parseVideoVariants({
      title: 'Anbil Avan - Vinnaithaandi Varuvaayaa',
      channelTitle: 'Label',
      durationSec: 300,
    });
    const r = matchVideo(variants, [
      song({
        title: 'Anbil Avan',
        artist: 'A.R. Rahman',
        album: 'Vinnaithaandi Varuvaayaa',
        durationSec: 300,
      }),
    ]);
    expect(r.best.parsed.title).toBe('Anbil Avan'); // the song, not the film
    expect(r.best.breakdown.artist).toBeNull(); // demoted from 0
    expect(r.best.breakdown.sanity).toBe(1); // counted as movie agreement
    expect(r.tier).toBe(TIER.AUTO);
  });

  it('still counts a genuinely wrong artist against the match', () => {
    // The demotion must not become a blanket amnesty: an artist that matches
    // neither the singer nor the album is real disagreement.
    const p = parseVideo({ title: 'Anbil Avan - Some Random Band', channelTitle: 'x', durationSec: 300 });
    const s2 = scoreCandidate(
      p,
      song({ title: 'Anbil Avan', artist: 'A.R. Rahman', album: 'Vinnaithaandi Varuvaayaa', durationSec: 300 }),
    );
    expect(s2.breakdown.artist).toBe(0);
  });

  it.each([
    ['Naan Pizhai Video', 'Naan Pizhai'],
    ['Kaagadada Doniyalli 8K', 'Kaagadada Doniyalli'],
    ['Venmathi Venmathiye Official', 'Venmathi Venmathiye'],
    ['Gira Gira Song', 'Gira Gira'],
    ['Poovukkul Official Quality Video', 'Poovukkul'],
    // …but a real title made of those words must survive.
    ['Video Games', 'Video Games'],
  ])('strips trailing decoration: %s', (raw, want) => {
    expect(cleanTitle(raw)).toBe(want);
  });
});

// From the 52% run — the three classes still blocking correct matches.
describe('defects found by the 52% run', () => {
  // Indian titles are romanised by whoever typed them. Doubled vowels, dropped
  // h's and -i/-y endings are normal variation, not different words, and exact
  // token matching missed the song entirely.
  it.each([
    ['Just Math Mathalli', 'Just Maath Maathali'],
    ['Oo Saathiya', 'O Saathiya'],
    ['Ulidavaru Kandante', 'Ulidavaru Kandanthe'],
    ['Uyire', 'Uyirey'],
  ])('matches transliteration variants: %s ~ %s', (a, b) => {
    expect(titleSimilarity(a, b)).toBeGreaterThanOrEqual(0.9);
  });

  it('does not collapse genuinely different titles', () => {
    expect(titleSimilarity('Kesariya', 'Naatu Naatu')).toBe(0);
    expect(tokensAlike('kesariya', 'kantara')).toBe(false);
  });

  // "Mugulu Nage - Title Track" put a LABEL in the artist slot, which scored 0
  // against the real singer and held a t=1 d=1 match at 0.611.
  it('treats a generic label in the artist slot as unknown', () => {
    const p = parseVideo({ title: 'Mugulu Nage - Title Track', channelTitle: 'x', durationSec: 300 });
    const r = matchVideo(parseVideoVariants({
      title: 'Mugulu Nage - Title Track', channelTitle: 'x', durationSec: 300,
    }), [song({ title: 'Mugulu Nage', artist: 'Sonu Nigam', durationSec: 300 })]);
    expect(r.best.breakdown.artist).toBeNull();
    expect(r.tier).toBe(TIER.AUTO);
    expect(p.title).toBeTruthy();
  });

  // "Inthandham Song - Sita Ramam" kept "Song" on the title AFTER the split,
  // dropping an otherwise exact match to 0.667.
  it('strips decoration on each side of the split, not just the whole string', () => {
    expect(stripTrailingDecoration('Inthandham Song')).toBe('Inthandham');
    const v = parseVideoVariants({ title: 'Inthandham Song - Sita Ramam', channelTitle: 'x' });
    expect(v.some(p => p.title === 'Inthandham')).toBe(true);
  });
});

// From the 58% run. The first two are defects I introduced with the
// transliteration fix — real data caught them within one round.
describe('defects found by the 58% run', () => {
  it('never scores a similarity above 1.0', () => {
    // "Venmathi Venmathiye" vs "Venmathiye" reported t=1.333: "venmathi"
    // matched "venmathiye" fuzzily, then "venmathiye" matched the SAME token
    // exactly. shared must never exceed the smaller set.
    expect(titleSimilarity('Venmathi Venmathiye', 'Venmathiye')).toBeLessThanOrEqual(1);
    expect(titleSimilarity('Venmathi Venmathiye', 'Venmathiye')).toBeCloseTo(0.667, 2);
  });

  it('does not treat a short title inside a much longer one as a match', () => {
    // Peppa Pig. "She's the Best" is fully contained in "She's The Greatest,
    // She's The Best Mummy Pig" and scored 0.92 — containment is only evidence
    // when the titles are comparable in length.
    const s2 = titleSimilarity("She's the Best", "She's The Greatest, She's The Best Mummy Pig");
    expect(s2).toBeLessThan(0.85);
  });

  it('still rewards containment when the lengths ARE comparable', () => {
    // The guard must not throw out the case it was built for.
    expect(titleSimilarity('Wheels On The Birthday Bus', 'The Wheels on the Bus'))
      .toBeGreaterThanOrEqual(0.9);
  });

  it('drops an orphan bracket left by a strip', () => {
    // Three KATSEYE rows arrived as "Bel Air (" — cosmetic for scoring, but it
    // reaches the review screen looking like a broken app.
    expect(cleanTitle('Bel Air (')).toBe('Bel Air');
    expect(cleanTitle('Kesariya (From "Brahmastra")')).toBe('Kesariya (From "Brahmastra")');
  });
});

describe('defects found by the first LIVE import', () => {
  // A real user, a real key, a real Tamil mix: 21 auto / 5 review / 1 unmatched
  // out of 27 usable. These come from reading that run's output rather than a
  // harness.

  it('strips a bare trailing "Lyric", not just "Lyrics" and "Lyrical"', () => {
    // The singular was simply missing from the alternation. Live title:
    // "Master - Andha Kanna Paathaakaa Lyric | Thalapathy Vijay | …" parsed to
    // the title "Andha Kanna Paathaakaa Lyric". It matched anyway — fuzzy
    // scoring absorbed the token — but "<song> Lyric | <cast>" is one of the
    // most common Tamil/Telugu label title shapes, so the drag was being paid
    // across a whole class of rows.
    expect(stripTrailingDecoration('Andha Kanna Paathaakaa Lyric')).toBe('Andha Kanna Paathaakaa');
    expect(stripTrailingDecoration('Andha Kanna Paathaakaa Lyrics')).toBe('Andha Kanna Paathaakaa');
    expect(stripTrailingDecoration('Andha Kanna Paathaakaa Lyrical')).toBe('Andha Kanna Paathaakaa');
  });

  it('recovers the exact title from the real live video title', () => {
    expect(cleanTitle('Master - Andha Kanna Paathaakaa Lyric | Thalapathy Vijay | Anirudh Ravichander | Lokesh Kanagaraj'))
      .toBe('Master - Andha Kanna Paathaakaa');
  });

  it('lifts that row to an exact title match instead of a fuzzy one', () => {
    // The point of the fix, stated as the score it changes.
    expect(titleSimilarity('Andha Kanna Paathaakaa Lyric', 'Andha Kanna Paathaakaa')).toBeLessThan(1);
    expect(titleSimilarity(cleanTitle('Andha Kanna Paathaakaa Lyric'), 'Andha Kanna Paathaakaa')).toBe(1);
  });

  it('does not eat a real word ending in "lyric"', () => {
    // Word-boundary only. Nothing here should touch a legitimate title.
    expect(stripTrailingDecoration('Panegyric')).toBe('Panegyric');
    expect(stripTrailingDecoration('Lyric Suite Movement')).toBe('Lyric Suite Movement');
  });
});

describe('defects found by the 53-row Telugu/Kannada measurement', () => {
  // Two real playlists through the dry-run harness: 62.3% auto, 26.4% review,
  // 11.3% unmatched — and, contrary to what we had been claiming, ZERO
  // zero-candidate rows. Romanised titles search fine; it is native SCRIPT that
  // the catalogue cannot answer.

  const match = (title, cands, durationSec = 330) =>
    matchVideo(parseVideoVariants({ title, channelTitle: '', durationSec, description: '' }), cands);

  describe('the movie in pipe segment 2 is evidence, not junk', () => {
    // The review pile's dominant cause. A "Full Video Song" is the film cut and
    // runs far longer than the audio track the catalogue holds, so duration —
    // the only corroboration available when no artist is known — fails, and a
    // PERFECT title match cannot reach auto. The film name sits right there in
    // the title, and cleanTitle was throwing it away.
    const SIR = [{ id: 'x', title: 'Mastaaru Mastaaru', artist: 'G.V. Prakash Kumar', album: 'SIR', durationSec: 243 }];

    it('recovers it, and that flips a correct match from review to auto', () => {
      const v = match('Mastaaru Mastaaru Full Video Song | SIR Telugu Movie | Dhanush', SIR);
      expect(v.best.breakdown.sanity).toBe(1);
      expect(v.tier).toBe(TIER.AUTO);
      // Duration still disagrees — the film cut is 87s longer. Sanity is what
      // carries it, which is the whole point.
      expect(v.best.breakdown.duration).toBeLessThan(0.9);
    });

    it('strips the language and the word "movie" from the segment', () => {
      expect(movieFromPipeSegments('X Full Video Song | SIR Telugu Movie | Dhanush')).toBe('SIR');
      expect(movieFromPipeSegments('Srivalli (Video) | Pushpa | Allu Arjun')).toBe('Pushpa');
      expect(movieFromPipeSegments('Kaagadada Doniyalli - Video Song | Kirik Party | Rakshit'))
        .toBe('Kirik Party');
    });

    it('an explicit (From "…") still wins over the pipe guess', () => {
      const [r] = parseVideoVariants({
        title: 'Undiporaadhey (From "Hushaaru") | Some Other Film | X', channelTitle: '',
      });
      expect(r.movie).toBe('Hushaaru');
    });

    it('costs nothing when segment 2 is not a film', () => {
      // A series name. It must simply fail to corroborate, exactly as a missing
      // movie does today — never invent agreement.
      const v = match('Gudugudiya Sedi Nodo | Courtyard Jam Sessions',
        [{ id: 'z', title: 'Gudugudiya Sedi Nodo', artist: 'Raghu Dixit', album: 'Jhankaar', durationSec: 300 }]);
      expect(v.best.breakdown.sanity).toBe(0);
    });

    it('does NOT match a short film name inside an unrelated album', () => {
      // The reason movie agreement is compared as token sets rather than
      // substrings: "SIR" is inside "Sirivennela". Harmless when the only movie
      // source was an explicit (From "…"); not harmless once movies are guessed,
      // because sanity > 0 is a route to AUTO — it would silently accept a wrong
      // track rather than merely nudge a score.
      const v = match('Mastaaru Full Video Song | SIR Telugu Movie | X',
        [{ id: 'y', title: 'Mastaaru', artist: 'Someone', album: 'Sirivennela', durationSec: 243 }]);
      expect(v.best.breakdown.sanity).toBe(0);
      expect(v.tier).toBe(TIER.REVIEW);
    });

    it('still agrees when the album merely extends the film name', () => {
      // Token-subset has to keep the real case it was protecting.
      const v = match('Srivalli (Video) | Pushpa | Allu Arjun',
        [{ id: 'p', title: 'Srivalli', artist: 'Sid Sriram', album: 'Pushpa: The Rise', durationSec: 240 }]);
      expect(v.best.breakdown.sanity).toBe(1);
    });
  });

  describe('hashtag compounds', () => {
    it('splits #SaradagaKasepaina, which scored 0.167 and went unmatched', () => {
      // tokens() splits on whitespace, so the glued hashtag was ONE token and
      // shared nothing with the catalogue's two.
      expect(cleanTitle('#SaradagaKasepaina Full Video Song | Paagal')).toBe('Saradaga Kasepaina');
      const v = match('#SaradagaKasepaina Full Video Song | Paagal Movie',
        [{ id: 's', title: 'Saradaga Kasepaina', artist: 'Karthik', album: 'Paagal', durationSec: 240 }]);
      expect(v.best.breakdown.title).toBe(1);
      expect(v.tier).not.toBe(TIER.UNMATCHED);
    });

    it('leaves a single-word hashtag alone — it already worked', () => {
      expect(cleanTitle('#Leharaayi Full Video | Most Eligible Bachelor')).toBe('Leharaayi');
    });

    it('does not guess at acronym runs', () => {
      // Only a lower→upper boundary splits, so "#ARRahman" is left intact
      // rather than mangled into "A R Rahman".
      expect(cleanTitle('#ARRahman Live')).toBe('ARRahman Live');
    });
  });

  describe('plural "Songs"', () => {
    it('strips it — "Audio Songs" survived whole and scored 0.000', () => {
      expect(cleanTitle('Evaraina Eppudaina Audio Songs | Jukebox | V'))
        .toBe('Evaraina Eppudaina');
    });

    it('does not strand a bare "Songs", the orphan the singular rule exists to stop', () => {
      // "Full Video Songs" used to strip only its head and leave "X Songs".
      expect(cleanTitle('Ninnu Kori Full Video Songs | Nani')).toBe('Ninnu Kori');
      expect(cleanTitle('X Full Songs | Y')).toBe('X');
    });
  });
});

describe('"Title Track", the Kannada/Telugu label shape', () => {
  // Four real titles from the user's Kannada playlists. The pipe-cut and the
  // "… Song" strips already handled three of them; the fourth exposed that
  // "Title Track" — a phrase GENERIC_TITLES has always known was meaningless —
  // survived cleaning, became an ARTIST via the "A - B" split, and spawned a
  // second reading titled "Title Track" that spent one of only two catalogue
  // searches per video (MAX_SEARCHES_PER_ITEM) on itself.

  const readings = (title) => parseVideoVariants({ title, channelTitle: '', durationSec: 240 });

  it('strips "Title Track" instead of promoting it to an artist', () => {
    expect(cleanTitle('Sapta Sagaradaache Ello - Title Track | Rakshit Shetty | Rukmini'))
      .toBe('Sapta Sagaradaache Ello');
    const [r] = readings('Sapta Sagaradaache Ello - Title Track | Rakshit Shetty');
    expect(r.title).toBe('Sapta Sagaradaache Ello');
    expect(r.artists).not.toContain('Title Track');
  });

  it('emits ONE reading, not a rival built on a phrase nobody released', () => {
    // The saving. Two readings meant two queries, and the second was
    // "Title Track <song>" — spending half this video's search budget on a
    // reading isGenericTitle rejects everywhere else in the codebase.
    expect(readings('Sapta Sagaradaache Ello - Title Track | Rakshit Shetty')).toHaveLength(1);
    expect(readings('Mugulu Nage - Title Track | Ganesh')).toHaveLength(1);
  });

  it('handles the bracketed form too', () => {
    expect(cleanTitle('Kesariya (Title Track)')).toBe('Kesariya');
    expect(cleanTitle('Kesariya [Title Song]')).toBe('Kesariya');
  });

  it('leaves no separator debris when the phrase leads', () => {
    // Caught by the existing suite the moment the strip was added:
    // "Title Track - Mugulu Nage" cleaned to "- Mugulu Nage".
    expect(cleanTitle('Title Track - Mugulu Nage')).toBe('Mugulu Nage');
    expect(readings('Title Track - Mugulu Nage')[0].title).toBe('Mugulu Nage');
  });

  it('still keeps BOTH readings when the ambiguity is real', () => {
    // The guard must not collapse the case the dual-reading design exists for.
    // "Tulasi - Sumedh K" is genuinely either order; neither side is generic.
    const v = readings('Tulasi - Sumedh K');
    expect(v).toHaveLength(2);
    expect(v.map(p => p.title)).toEqual(expect.arrayContaining(['Tulasi', 'Sumedh K']));
  });

  it('leaves the three titles that already worked exactly as they were', () => {
    // No-regression, stated as the user's own examples.
    expect(cleanTitle('Ee Tanuvu Ninnade')).toBe('Ee Tanuvu Ninnade');
    expect(cleanTitle('Kaagadada Doniyalli - Video Song | Kirik Party | Rakshit Shetty'))
      .toBe('Kaagadada Doniyalli');
    expect(cleanTitle('Gudugudiya Sedi Nodo Raghu Dixit | Courtyard Jam Sessions'))
      .toBe('Gudugudiya Sedi Nodo Raghu Dixit');
  });

  it('does not eat "title" or "track" used as real words', () => {
    expect(cleanTitle('Track 9')).toBe('Track 9');
    expect(cleanTitle('The Title')).toBe('The Title');
    expect(cleanTitle('Soundtrack')).toBe('Soundtrack');
  });
});

describe('artist credit', () => {
  // MEASURED: three KATSEYE rows capped at 0.811 because an EXACT, complete
  // artist match scored 0.6 — full credit needed two shared tokens, which a
  // one-word name can never reach.
  it('gives full credit for a complete single-word artist match', () => {
    expect(artistOverlap(['KATSEYE'], 'Katseye')).toBe(1);
    expect(artistOverlap(['Milano'], 'Milano')).toBe(1);
  });

  // …but the surname case must stay weak: half of Bollywood shares one.
  it('keeps a lone surname partial', () => {
    expect(artistOverlap(['Singh'], 'Arijit Singh')).toBe(0.6);
  });

  it('tolerates transliteration in artist names too', () => {
    expect(artistOverlap(['Arjit Singh'], 'Arijit Singh')).toBe(1);
  });

  it('still reports genuine disagreement as zero', () => {
    expect(artistOverlap(['Nobody'], 'Someone Else')).toBe(0);
  });
});
